export enum ErrorMap {
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    CONNECTION_ERROR = 'CONNECTION_ERROR',
    INVALID_URL = 'INVALID_URL',
    FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
    NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
    SERVER_ERROR = 'SERVER_ERROR',
    CANNOT_CREATE_MODEL = 'CANNOT_CREATE_MODEL',
    CANNOT_FIND_MODEL = 'CANNOT_FIND_MODEL',
    CANNOT_UPDATE_MODEL = 'CANNOT_UPDATE_MODEL',
    CANNOT_DELETE_MODEL = 'CANNOT_DELETE_MODEL',
}